<?php

namespace Oacc\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ShipRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ShipRepository extends EntityRepository
{
}
