<?php

namespace Oacc\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SquadronRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class SquadronRepository extends EntityRepository
{
}
